save intermediate changes

diff --git a/source_me b/source_me
--- a/source_me
+++ b/source_me
@@ -1,196 +1,55 @@
-
-
-######################### DO NOT MODIFY THIS FILE #########################
-
-#   JCF, Aug-27-2019
-
-#   This sourcefile needs to be sourced before running DAQInterface. 
-
-#   Consequences of sourcing are:
-#
-#   * An alias is created so the command "DAQInterface" will run DAQInterface
-#
-#   * The output of a DAQInterface session will be saved in a logfile
-#     referred to by $DAQINTERFACE_LOGFILE
-#
-#   * A user-defined sourcefile referred to by
-#     $DAQINTERFACE_USER_SOURCEFILE will also be sourced - see below
-#     under "Requirements" for more on this
-
-#   Requirements to be met before the sourcing are:
-#
-#   * DAQInterface needs to have been successfully set up as a ups product
-#
-#   * The sourcefile has not yet been sourced successfully in the
-#     environment
-#
-#   * The user-defined sourcefile name needs be referred to
-#     by the environment variable $DAQINTERFACE_USER_SOURCEFILE. The
-#     user-defined sourcefile must actually be owned by the active user
-#     in the environment ($USER), and within its body it must export an
-#     environment variable called "DAQINTERFACE_USER_SOURCEFILE_ERRNO"
-#     and set it to 0 to let this "parent" sourcefile know that the user
-#     sourcefile was sourced correctly. It also needs to set DAQINTERFACE_SETTINGS 
-#     and DAQINTERFACE_KNOWN_BOARDREADERS_LIST.
-
-######################################################################
-
-
-
-###############TESTS WHICH CAN BE RUN ON THIS SCRIPT##################
-
-# Tests DAQInterface developers can run on this script include:
-
-# -Make sure this script can't be edited without changing its permissions
-
-# -Make sure you can't source this script again in the same environment
-# after it's been successfully sourced
-
-# -Make sure you can't source this script from within its own
-# directory (most likely risk is someone doesn't bother setting up a
-# separate DAQInterface working area and instead tries to run out
-# of the git repo area)
-
-# -Make sure DAQINTERFACE_PROCESS_MANAGEMENT_METHOD,
-# DAQINTERFACE_LOGDIR, DAQINTERFACE_PARTITION_NUMBER and
-# DAQINTERFACE_FHICL_DIRECTORY all have reasonable defaults
-
-# -And that if users in their $DAQINTERFACE_USER_SOURCEFILE script
-# override DAQINTERFACE_PROCESS_MANAGEMENT_METHOD,
-# DAQINTERFACE_LOGDIR, DAQINTERFACE_PARTITION_NUMBER and
-# DAQINTERFACE_FHICL_DIRECTORY, that these variables get picked up 
-
-# -Make sure that typing "DAQInterface" after a successful sourcing of
-# this script launches DAQInterface, and that it uses the environment
-# variable values you expect
-
-# -Make sure this script fails if DAQINTERFACE_USER_SOURCEFILE isn't
-# the name of an existing file (including failure if the
-# now-deprecated "IGNORED" value is chosen)
-
-# -Make sure this script fails if the owner of
-# $DAQINTERFACE_USER_SOURCEFILE isn't the current user
-
-# -Make sure this script doesn't set up the DAQInterface environment if
-# $DAQINTERFACE_USER_SOURCEFILE doesn't set an environment variable
-# DAQINTERFACE_USER_SOURCEFILE_ERRNO to 0
-
-# -Make sure this script fails if DAQINTERFACE_SETTINGS or
-#  DAQINTERFACE_KNOWN_BOARDREADERS_LIST doesn't get defined in
-#  $DAQINTERFACE_USER_SOURCEFILE, or if they're defined in
-#  $DAQINTERFACE_USER_SOURCEFILE but don't refer to files which exist
-
-#########################END OF LIST OF TESTS#########################
-
-# JCF, Aug-2-2019
-# Guard against attempts to edit this file
-chmod 444 $ARTDAQ_DAQINTERFACE_DIR/source_me > /dev/null 2>&1
+#!/usr/bin/bash
 
 function cleanup() {
     
-    export PATH=$( echo $PATH | sed -r 's!'${ARTDAQ_DAQINTERFACE_DIR}/bin':*!!'  )
+    export PATH=$(echo $PATH | sed -r 's!'${TFM_DIR}/bin':*!!')
 
-    unset DAQINTERFACE_LOGDIR
-    unset DAQINTERFACE_LOGFILE
-    unset DAQINTERFACE_USER_SOURCEFILE_ERRNO
-    unset DAQINTERFACE_STANDARD_SOURCEFILE_SOURCED
-    unset DAQINTERFACE_TTY
-    unset DAQINTERFACE_PORT
-
-    unalias DAQInterface
-
-    cat<<EOF
-
-n.b. As there's no guarantee your environment is the same as before
-this unsucessful source attempt, it's recommended you enter a clean
-environment (e.g., log out and then back in) before attempting to
-source this script again.
-
-EOF
-
+    unset TFM_LOGDIR
+    unset TFM_LOGFILE
+    unset TFM_USER_SOURCEFILE_ERRNO
+    unset TFM_STANDARD_SOURCEFILE_SOURCED
+    unset TFM_TTY
+    unset TFM_PORT
 }
 
-if [[ -n $DAQINTERFACE_STANDARD_SOURCEFILE_SOURCED ]]; then
-   echo "You appear to have already sourced this script in this shell; will do nothing"
+if [[ -n $TFM_STANDARD_SOURCEFILE_SOURCED ]]; then
+   echo "already sourced. do nothing"
    return 1
 fi
 
-if [[ -n $ARTDAQ_DAQINTERFACE_VERSION ]] ; then
-
-    echo "Using ups-installed DAQInterface, version \"$ARTDAQ_DAQINTERFACE_VERSION\""
-
-else
-
-    echo "DAQInterface does not appear to have been set up as a ups product; will do nothing"
-    return 1
+if [ -n $TFM_VERSION ] ; then echo TFM_VERSION=$TFM_VERSION
+                         else echo "TFM not setup, bail out" ; return 1
 fi
 
-if [[ "$PWD" == "$ARTDAQ_DAQINTERFACE_DIR" ]]; then
-    
-    cat<<EOF
-You appear to be trying to source this script within its own directory
-(i.e., within either the ups product directory or the git repo);
-please read the DAQInterface Manual at
-https://cdcvs.fnal.gov/redmine/projects/artdaq-utilities/wiki/Artdaq-daqinterface
-to learn how to properly set up the DAQInterface environment. 
-EOF
+export TFM_TTY=$(tty | sed -r 's!/dev/!!')
 
-    return 1
-fi
-
-# Eric F: "I hacked all my code on a host with no name"
-
-if [[ -z $HOSTNAME ]]; then
-   echo
-   echo -n "HOSTNAME not defined, will define it here as "
-   export HOSTNAME=$( hostname )
-   echo "\"$HOSTNAME\""
-   echo
-fi
-
-
-export DAQINTERFACE_TTY=$( tty | sed -r 's!/dev/!!' )
-
-if ! [[ "$DAQINTERFACE_TTY" =~ pts/[0-9]+ ]]; then
-
-cat<<EOF >&2
-
+if ! [[ "$TFM_TTY" =~ pts/[0-9]+ ]]; then
+    cat<<EOF >&2
 WARNING: unable to determine tty. While this will not affect
 actual datataking, any DAQInterface launched in this environment
 may have problems with sending output to a MessageViewer instance
-
 EOF
-
 fi
 
-if [[ -z $ARTDAQ_BASE_PORT ]]; then
-   export ARTDAQ_BASE_PORT=10000
-fi
+if [ -z $TFM_BASE_PORT           ] ; then export TFM_BASE_PORT=10000          ; fi
+if [ -z $TFM_PORTS_PER_PARTITION ] ; then export TFM_PORTS_PER_PARTITION=1000 ; fi
 
-if [[ -z $ARTDAQ_PORTS_PER_PARTITION ]]; then
-   export ARTDAQ_PORTS_PER_PARTITION=1000
-fi
+export PATH=$TFM_DIR/bin:$PATH
 
+if [[ -n $TFM_USER_SOURCEFILE ]]; then
 
-alias DAQInterface="$ARTDAQ_DAQINTERFACE_DIR/bin/DAQInterface.sh"
-
-
-export PATH=$ARTDAQ_DAQINTERFACE_DIR/bin:$PATH
-
-if [[ -n $DAQINTERFACE_USER_SOURCEFILE ]]; then
-
-   if [[ "$DAQINTERFACE_USER_SOURCEFILE" != "IGNORED" && -e $DAQINTERFACE_USER_SOURCEFILE ]]; then
-       user_sourcefile_owner=$( ls -l $DAQINTERFACE_USER_SOURCEFILE | awk '{print $3}' )
+   if [[ "$TFM_USER_SOURCEFILE" != "IGNORED" && -e $TFM_USER_SOURCEFILE ]]; then
+       user_sourcefile_owner=$( ls -l $TFM_USER_SOURCEFILE | awk '{print $3}' )
 
        if [[ "$user_sourcefile_owner" == "$USER" ]]; then
-       	  . $DAQINTERFACE_USER_SOURCEFILE
+       	  . $TFM_USER_SOURCEFILE
        else
 
 cat<<heredoc
 
 	   ERROR: Current user "$USER" is not the same as the owner of
-           ${DAQINTERFACE_USER_SOURCEFILE}; source of
-           $DAQINTERFACE_USER_SOURCEFILE will not take place
+           ${TFM_USER_SOURCEFILE}; source of
+           $TFM_USER_SOURCEFILE will not take place
 
 heredoc
 
@@ -198,26 +57,26 @@ heredoc
            return 1
 
        fi
-   elif [[ "$DAQINTERFACE_USER_SOURCEFILE" != "IGNORED" && ! -e $DAQINTERFACE_USER_SOURCEFILE ]]; then
+   elif [[ "$TFM_USER_SOURCEFILE" != "IGNORED" && ! -e $TFM_USER_SOURCEFILE ]]; then
 
 cat<<heredoc
 
-	ERROR: DAQINTERFACE_USER_SOURCEFILE environment variable has been
+	ERROR: TFM_USER_SOURCEFILE environment variable has been
 	set, but the would-be sourcefile it refers to,
-	"$DAQINTERFACE_USER_SOURCEFILE", doesn't exist. 
+	"$TFM_USER_SOURCEFILE", doesn't exist. 
 
 heredoc
 
         cleanup
 	return 1
-   else   # $DAQINTERFACE_USER_SOURCEFILE == IGNORED, so we don't source a user-defined script
+   else   # $TFM_USER_SOURCEFILE == IGNORED, so we don't source a user-defined script
 
 cat<<EOF
 
-       ERROR: DAQINTERFACE_USER_SOURCEFILE environment variable has
+       ERROR: TFM_USER_SOURCEFILE environment variable has
        been set to "IGNORED"; while previously this meant that this
        script would not source a user-defined script referred to by
-       the DAQINTERFACE_USER_SOURCEFILE variable, this option is now
+       the TFM_USER_SOURCEFILE variable, this option is now
        deprecated
 
 EOF
@@ -229,7 +88,7 @@ else
 
 cat<<heredoc
 
-	ERROR: the DAQINTERFACE_USER_SOURCEFILE environment variable
+	ERROR: the TFM_USER_SOURCEFILE environment variable
 	must be set, either to the name of the user-defined sourcefile
 	you wish to have sourced, or to "IGNORED" if you don't want to
 	source a user-defined sourcefile
@@ -240,15 +99,15 @@ heredoc
    return 1
 fi
 
-if [[ -z $DAQINTERFACE_USER_SOURCEFILE_ERRNO ]] ; then
+if [[ -z $TFM_USER_SOURCEFILE_ERRNO ]] ; then
     
 cat<<heredoc
 
-      ERROR: the DAQINTERFACE_USER_SOURCEFILE_ERRNO environment
+      ERROR: the TFM_USER_SOURCEFILE_ERRNO environment
       variable doesn't exist; this needs to be set in the user script
-      referred to by the DAQINTERFACE_USER_SOURCEFILE environment
+      referred to by the TFM_USER_SOURCEFILE environment
       variable. Setting the variable to "0" in
-      $DAQINTERFACE_USER_SOURCEFILE implies success, anything else
+      $TFM_USER_SOURCEFILE implies success, anything else
       implies a failure and this script will consequently *not* set up
       the DAQInterface environment.
 
@@ -257,36 +116,36 @@ heredoc
     cleanup
     return 1
 
-elif [[ "$DAQINTERFACE_USER_SOURCEFILE_ERRNO" != "0" ]] ; then
+elif [[ "$TFM_USER_SOURCEFILE_ERRNO" != "0" ]] ; then
 
 cat<<heredoc
 
-      ERROR: the DAQINTERFACE_USER_SOURCEFILE_ERRNO environment
+      ERROR: the TFM_USER_SOURCEFILE_ERRNO environment
       variable was set by the user-defined source script
-      "$DAQINTERFACE_USER_SOURCEFILE" with a value of
-      $DAQINTERFACE_USER_SOURCEFILE_ERRNO; anything nonzero is considered to be an error.
+      "$TFM_USER_SOURCEFILE" with a value of
+      $TFM_USER_SOURCEFILE_ERRNO; anything nonzero is considered to be an error.
 heredoc
 
      cleanup
      return 1
 fi
 
-if [[ -n $DAQINTERFACE_SETTINGS ]]; then
+if [[ -n $TFM_SETTINGS ]]; then
     
-    if [[ ! -e $DAQINTERFACE_SETTINGS ]]; then
+    if [[ ! -e $TFM_SETTINGS ]]; then
 
-	echo "ERROR: the DAQINTERFACE_SETTINGS environment variable doesn't point to a file which exists"
+	echo "ERROR: the TFM_SETTINGS environment variable doesn't point to a file which exists"
 	cleanup
 	return 1
     fi
 
-    export DAQINTERFACE_SETUP_FHICLCPP=$( dirname $DAQINTERFACE_SETTINGS )/.setup_fhiclcpp
+    export TFM_SETUP_FHICLCPP=$( dirname $TFM_SETTINGS )/.setup_fhiclcpp
 else
 
     cat<<EOF
 
-ERROR: the environment variable DAQINTERFACE_SETTINGS hasn't been
-defined in $DAQINTERFACE_USER_SOURCEFILE. Please read the DAQInterface
+ERROR: the environment variable TFM_SETTINGS hasn't been
+defined in $TFM_USER_SOURCEFILE. Please read the DAQInterface
 Manual at
 https://cdcvs.fnal.gov/redmine/projects/artdaq-utilities/wiki/Artdaq-daqinterface
 to learn how to properly set up the DAQInterface environment.
@@ -301,22 +160,22 @@ fi
 
 # At this point, set various environment variables DAQInterface needs
 # to reasonable defaults if they weren't already set in
-# $DAQINTERFACE_USER_SOURCEFILE - or complain if there's no reasonable
+# $TFM_USER_SOURCEFILE - or complain if there's no reasonable
 # default
 
-if [[ -z $DAQINTERFACE_PARTITION_NUMBER ]]; then
-   export DAQINTERFACE_PARTITION_NUMBER=0
+if [[ -z $TFM_PARTITION_NUMBER ]]; then
+   export TFM_PARTITION_NUMBER=0
 fi
 
-if [[ -z $DAQINTERFACE_PROCESS_MANAGEMENT_METHOD ]]; then
-   export DAQINTERFACE_PROCESS_MANAGEMENT_METHOD="direct"
+if [[ -z $TFM_PROCESS_MANAGEMENT_METHOD ]]; then
+   export TFM_PROCESS_MANAGEMENT_METHOD="direct"
 fi
 
-if [[ -z $DAQINTERFACE_KNOWN_BOARDREADERS_LIST ]]; then
+if [[ -z $TFM_KNOWN_BOARDREADERS_LIST ]]; then
     cat<<EOF
 
-ERROR: the environment variable DAQINTERFACE_KNOWN_BOARDREADERS_LIST
-hasn't been defined in $DAQINTERFACE_USER_SOURCEFILE. Please read the
+ERROR: the environment variable TFM_KNOWN_BOARDREADERS_LIST
+hasn't been defined in $TFM_USER_SOURCEFILE. Please read the
 DAQInterface Manual at
 https://cdcvs.fnal.gov/redmine/projects/artdaq-utilities/wiki/Artdaq-daqinterface
 to learn how to properly set up the DAQInterface environment.
@@ -326,65 +185,56 @@ EOF
 cleanup
 return 1
 
-elif [[ ! -e $DAQINTERFACE_KNOWN_BOARDREADERS_LIST ]]; then
+elif [[ ! -e $TFM_KNOWN_BOARDREADERS_LIST ]]; then
 
-    echo "ERROR: the DAQINTERFACE_KNOWN_BOARDREADERS_LIST environment variable doesn't point to a file which exists"
+    echo "ERROR: the TFM_KNOWN_BOARDREADERS_LIST environment variable doesn't point to a file which exists"
     cleanup
     return 1
 fi
 
-if [[ -z $DAQINTERFACE_FHICL_DIRECTORY ]]; then
+if [[ -z $TFM_FHICL_DIRECTORY ]]; then
 
-    export DAQINTERFACE_FHICL_DIRECTORY="$PWD/simple_test_config"
+    export TFM_FHICL_DIRECTORY="$PWD/simple_test_config"
 
     cat<<EOF
 
-WARNING: the environment variable DAQINTERFACE_FHICL_DIRECTORY hasn't
-been defined in $DAQINTERFACE_USER_SOURCEFILE, so we're going to
-assume the default configuration area is $DAQINTERFACE_FHICL_DIRECTORY
+WARNING: the environment variable TFM_FHICL_DIRECTORY hasn't
+been defined in $TFM_USER_SOURCEFILE, so we're going to
+assume the default configuration area is $TFM_FHICL_DIRECTORY
 EOF
 fi
 
-if [[ ! -e "$DAQINTERFACE_FHICL_DIRECTORY" && "$DAQINTERFACE_FHICL_DIRECTORY" != "IGNORED" ]]; then
+if [[ ! -e "$TFM_FHICL_DIRECTORY" && "$TFM_FHICL_DIRECTORY" != "IGNORED" ]]; then
 
 cat<<EOF
 
 ERROR: unable to find the FHiCL directory referred to by the
-DAQINTERFACE_FHICL_DIRECTORY environment variable,
-$DAQINTERFACE_FHICL_DIRECTORY
+TFM_FHICL_DIRECTORY environment variable,
+$TFM_FHICL_DIRECTORY
 EOF
 
 cleanup
 return 1
 fi
 
-if [[ -z $DAQINTERFACE_LOGDIR ]]; then
-   export DAQINTERFACE_LOGDIR=/tmp/daqinterface_${USER}
-fi
+if [[ -z $TFM_LOGDIR ]]; then export TFM_LOGDIR=/tmp/tfm_${USER} ; fi
 
-
-mkdir -p $DAQINTERFACE_LOGDIR
-
-# If you (the developer, otherwise you shouldn't be editing this file)
-# change the format of DAQINTERFACE_LOGFILE, make sure this change is
-# reflected in the information message that appears after source-ing
-# this script
-
-export DAQINTERFACE_LOGFILE=$DAQINTERFACE_LOGDIR/DAQInterface_partition\${DAQINTERFACE_PARTITION_NUMBER}.log
-
-
+mkdir -p $TFM_LOGDIR
+#------------------------------------------------------------------------------
+# assume 100 partitions is enough
+#------------------------------------------------------------------------------
+export TFM_LOGFILE=$TFM_LOGDIR/partition_`printf "%02i" $TFM_PARTITION_NUMBER`.log
 
 cat<<EOF
 * The command was successful
 * To launch, just type "DAQInterface &" (excluding quotes, ampersand optional)
-* Output will be logged in ${DAQINTERFACE_LOGDIR}/DAQInterface_partition<N>.log, where <N> 
+* Output will be logged in ${TFM_LOGDIR}/DAQInterface_partition<N>.log, where <N> 
   is the partition the DAQInterface instance is on
 * You're encouraged to read the DAQInterface Manual at https://cdcvs.fnal.gov/redmine/projects/artdaq-utilities/wiki/Artdaq-daqinterface
 EOF
  
 echo
 
-export DAQINTERFACE_STANDARD_SOURCEFILE_SOURCED=true
+export TFM_STANDARD_SOURCEFILE_SOURCED=true
 
 return 0
-
